# Generated by Django 4.1.7 on 2023-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(default=0)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.PositiveIntegerField(default=1000, unique=True)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('speciality', models.CharField(choices=[('Cardiologist', 'Cardiologist speciality'), ('Dermatologist', 'Dermatologist speciality')], default='Cardiologist', max_length=100)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
    ]
